---
title: spatPomp, an R package for statistical inference for spatiotemporal partially observed Markov processes
output:
  html_document:
    css: "pompstyle.css"
---

<span class="firstcharacter">**spatPomp**</span> concerns inference for nonlinear partially-observed Markov process models having a spatial unit structure in addition to the temporal Markovian property of the latent process.
Such a model is called a SpatPOMP.
For example, ecological metapopulation models consist of spatial units corresponding to distinct, interacting sub-populations.
Each unit may itself consist of multiple interacting species.
In **spatPomp**, models can be represented by specifying the latent dynamic process and how it is measured.
The **spatPomp** package builds on **pomp**, and its base class, `spatPomp` extends the **pomp** class `pomp`.
Therefore, all algorithms and methods provided by **pomp** are accessible in **spatPomp**.
However, practical analysis of high-dimensional systems can take advantage of the additional unit structure that POMP models do not necessarily possess.

Algorithms currently provided by  **spatPomp** include the following:

- Guided intermediate resampling filter, `girf`
- Block particle filter, `bpfilter`
- Adapted bagged filter, `abf`
- Ensemble Kalman filter, `enkf`
- Iterated GIRF for parameter estimation, `igirf`
- Iterated bpfilter for parameter estimation, `ibpf`
- Iterated ensemble Kalman filter for parameter estimation, `ienkf`

In addition, the particle filter provided by [**pomp**](https://kingaa.github.io/pomp/) as `pfilter` and the corresponding iterated filter, `mif2`, are useful for validating **spatPomp** models and workflows on small subsets the spatial units.

**spatPomp** is currently in development. All are welcome to contribute methods or models, or any other feedback.   Please let the developers know if you find **spatPomp** useful and if you publish results obtained using it!

The latest development version of **spatPomp** is available on [GitHub](https://github.com/kidusasfaw/spatPomp) and versions are occasionally uploaded to [CRAN](https://cran.rstudio.com/web/packages/spatPomp). Other relevant resources are:

- [A tutorial on spatiotemporal partially observed Markov process models via the R package spatPomp](vignettes/spatPomp.pdf)
- [A tutorial on the iterated block particle filter](vignettes/ibpf.pdf)

Papers using **spatPomp** include the following:

- Ionides, E. L., Asfaw, K., Park, J.,  and King, A. A. (2023). 
  Bagged filters for partially observed interacting systems.
  _Journal of the American Statistical Association,_ 118, 1078-1089.
  [doi](https://doi.org/10.1080/01621459.2021.1974867).
  [arxiv](https://arxiv.org/abs/2002.05211).
  [code](https://github.com/ionides/bagged_filters).
- Ionides, E. L.,  Ning, N. and Wheeler, J. (2022).
  An iterated block particle filter for inference on coupled dynamic systems with shared and unit-specific parameters.
  _Statistica Sinica,_
  prepublished online.
  [doi](https://doi.org/10.5705/ss.202022.0188).
  [arxiv](https://arxiv.org/abs/2206.03837).
  [code](https://github.com/ionides/ibpf_article).
- Li, J., E. L. Ionides, A. A., King, M. Pascual and N. Ning (2024). Inference on spatiotemporal dynamics for coupled biological populations. _Journal of the Royal Society Interface_ 21(216), 20240217.
  [doi](https://doi.org/10.1098/rsif.2024.0217).
  [arxiv](https://arxiv.org/abs/2311.06702).
  [code](https://github.com/jifanli/metapop_article).
  [software](https://github.com/jifanli/metapoppkg)
- Ning, N. and Ionides, E. L. (2023). Iterated block particle filter for high-dimensional parameter learning: Beating the curse of dimensionality. _Journal of Machine Learning Research_ 24(82), 1-76.
[pdf](https://jmlr.org/papers/v24/21-1253.pdf). 
[arxiv](https://arxiv.org/abs/2110.10745v3"><i>arxiv</i></a>).
- Wheeler, J., Rosengart, A. L., Jiang, Z., Tan, K., Treutle, N. and Ionides, E. L. (2024).
  Informing policy via dynamic models: Cholera in Haiti.
  _PLOS Computational Biology_ 20(4), e1012032.
  [doi](https://doi.org/10.1371/journal.pcbi.1012032).
  [arxiv](https://doi.org/10.48550/arXiv.2301.08979).
  [code](https://github.com/jeswheel/haiti_article).
  [software](https://github.com/jeswheel/haitipkg).
- Zhang, B., Huang, W., Pei, S., Zeng, J., Shen, W., Wang, D., Wang, G., Chen, T., Yang, L., Cheng, P., Wang, D., Shu, Y., & Du, X. (2022). Mechanisms for the circulation of influenza A (H3N2) in China: A spatiotemporal modelling study. _PLOS Pathogens_, 18(12), e1011046.
[doi](https://doi.org/10.1371/journal.ppat.1011046).

